changes to adopt to recent kube-burner changes
Error: if any flags in the group [es-server metrics-endpoint] are set none of the others can be; [es-server metrics-endpoint] were all set

Signed-off-by: Murali Krishnasamy <mukrishn@redhat.com>